drop table ADMIN.PROJECT_DANGKI;
drop table ADMIN.PROJECT_PHANCONG;
drop table ADMIN.PROJECT_SINHVIEN;
drop table ADMIN.PROJECT_NHANSU;
drop table ADMIN.PROJECT_KHMO;
drop table ADMIN.PROJECT_HOCPHAN;
drop table ADMIN.PROJECT_DONVI;
