--Tao role nhan vien giao vu
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
create role TRGDONVI;
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;

--NHU MOT NGUOI DUNG CO VAI TRO GIANG VIEN
grant GIANGVIEN to TRGDONVI;
grant connect to GIANGVIEN;

--TAO VIEW DU LIEU PHAN CONG DOI VOI CAC HOC PHAN DUOC 
--PHU TRACH CHUYEN MON BOI DON VI MA MINH LAM TRUONG
create or replace view ADMIN.UV_TRGDONVI_PHANCONG
as
    select PC.*
    from ADMIN.PROJECT_PHANCONG PC, ADMIN.PROJECT_HOCPHAN HP, ADMIN.PROJECT_DONVI DV
    where PC.MAHP = HP.MAHP
        and HP.MADV = DV.MADV
        and DV.TRGDV = SYS_CONTEXT('USERENV','SESSION_USER');

--Grant quyen THEM, XOA, SUA TREN VIEW ADMIN.UV_TRGDONVI_PHANCONG cho TRUONG DON VI
grant INSERT, DELETE, UPDATE on ADMIN.UV_TRGDONVI_PHANCONG to TRGDONVI;
grant INSERT, UPDATE on ADMIN.UV_TRGDONVI_PHANCONG to TRGDONVI;
        
--TAO VIEW DU LIEU PHAN CONG GIANG DAY CUA CAC GIANG VIEN THUOC CAC DON VI MA MINH LAM TRUONG

create or replace view ADMIN.UV_TRGDONVI_XEMPHANCONG
as
    select PC.*
    from ADMIN.PROJECT_PHANCONG PC, ADMIN.PROJECT_NHANSU NS, ADMIN.PROJECT_DONVI DV
    where PC.MAGV = NS.MANV
        and NS.DONVI = DV.MADV
        and DV.TRGDV = SYS_CONTEXT('USERENV','SESSION_USER');
        
--Grant quyen XEM TREN ADMIN.UV_TRGDONVI_XEMPHANCONG cho TRUONG DON VI

grant SELECT on ADMIN.UV_TRGDONVI_XEMPHANCONG to TRGDONVI;

declare
    cursor cur_TRGDONVI is (select * from ADMIN.PROJECT_NHANSU where VAITRO = 'TRGDONVI');
    STRSQL varchar2(1000);
    result boolean;
begin
    for row_TRGDONVI in cur_TRGDONVI
    loop
        result := admin.isUserExists(row_TRGDONVI.MANV);
        if(result = false) then
            STRSQL := 'CREATE USER ' || row_TRGDONVI.MANV || ' identified by 123';
            EXECUTE IMMEDIATE (STRSQL);
        end if;
        STRSQL := 'GRANT TRGDONVI to ' || row_TRGDONVI.MANV;
        EXECUTE IMMEDIATE (STRSQL);
    end loop;
end;

