--Tao role nhan vien giao vu
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
create role TRUONGDONVI;
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;

--NHU MOT NGUOI DUNG CO VAI TRO GIANG VIEN
grant GIANGVIEN to TRUONGDONVI;
grant connect to GIANGVIEN;

--TAO VIEW DU LIEU PHAN CONG DOI VOI CAC HOC PHAN DUOC 
--PHU TRACH CHUYEN MON BOI DON VI MA MINH LAM TRUONG
create or replace view ADMIN.UV_TRUONGDONVI_PHANCONG
as
    select PC.*
    from ADMIN.PROJECT_PHANCONG PC, ADMIN.PROJECT_HOCPHAN HP, ADMIN.PROJECT_DONVI DV
    where PC.MAHP = HP.MAHP
        and HP.MADV = DV.MADV
        and DV.TRGDV = SYS_CONTEXT('USERENV','SESSION_USER');

--Grant quyen THEM, XOA, SUA TREN VIEW ADMIN.UV_TRUONGDONVI_PHANCONG cho TRUONG DON VI
grant INSERT, DELETE, UPDATE on ADMIN.UV_TRUONGDONVI_PHANCONG to TRUONGDONVI;
        
--TAO VIEW DU LIEU PHAN CONG GIANG DAY CUA CAC GIANG VIEN THUOC CAC DON VI MA MINH LAM TRUONG

create or replace view ADMIN.UV_TRUONGDONVI_XEMPHANCONG
as
    select PC.*
    from ADMIN.PROJECT_PHANCONG PC, ADMIN.PROJECT_NHANSU NS, ADMIN.PROJECT_DONVI DV
    where PC.MAGV = NS.MANV
        and NS.DONVI = DV.MADV
        and DV.TRGDV = SYS_CONTEXT('USERENV','SESSION_USER');
        
--Grant quyen XEM TREN ADMIN.UV_TRUONGDONVI_XEMPHANCONG cho TRUONG DON VI

grant SELECT on ADMIN.UV_TRUONGDONVI_XEMPHANCONG to TRUONGDONVI;



