ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
create role TRGKHOA;
--drop role TRGKHOA;
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;

--NHU MOT NGUOI DUNG CO VAI TRO GIANG VIEN
grant GIANGVIEN to TRGKHOA;
grant connect to TRGKHOA;

--TAO VIEW TREN QUAN HE PHAN CONG DOI VOI CAC HOC PHAN QUAN LY BOI DON VI VAN PHONG KHOA
create or replace view ADMIN.UV_TRGKHOA_PHANCONG
as
    select PC.*
    from ADMIN.PROJECT_PHANCONG PC, ADMIN.PROJECT_HOCPHAN HP, ADMIN.PROJECT_DONVI DV
    where PC.MAHP = HP.MAHP
        AND HP.MADV = DV.MADV
        AND dv.tendv = 'VP KHOA';
        
--THEM, XOA, CAP, NHAT ADMIN.UV_TRGKHOA_PHANCONG
grant SELECT, INSERT, DELETE, UPDATE on ADMIN.UV_TRGKHOA_PHANCONG to TRGKHOA;

--XEM, THEM, XOA, SUA, TREN BANG NHAN SU
grant SELECT, INSERT, DELETE, UPDATE on ADMIN.PROJECT_NHANSU to TRGKHOA;

--XEM TAT CA CAC BANG
grant select any table to TRGKHOA;

create user NV003 identified by 123;
grant TRGKHOA to NV003;